### ISSUE TITLE
Windows: Gallery position selection

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion-module-zoom-osc-iso#1]
I'm showing on the first 2 buttons (buttons are correct, showing position 1 and 2) and the other 2 participants aren't showing on the buttons. (variables all look right in the names). I only have 3 people in the call right now, do I need more to have that work properly?
Using Windows version 4.1.0, Ryan Dillis

**Comment by JeffreyDavidsz** [comment]
@Rdillis let me know with the new build and settings if this has been fixed

**Comment by Rdillis** [comment]
This is working with the new build. Names populate correctly, I can drag to re-order and they move as expected.
