### ISSUE TITLE
Selected Participant is randomly being unselected with no interaction

### ISSUE THREAD

**Issue by digitaldrummerj** [bitfocus/companion-module-zoom-osc-iso#112]
While running an event, I would select a participant and then I would come back a bit later and the participant was no longer selected.  

ZoomOSC 4.2 on Mac M2 Mini
Companion v3.0.0+5780-beta-bb541a1a but I am running the latest ZoomOSC main branch on my machine.

**Comment by digitaldrummerj** [comment]
@JeffreyDavidsz @AndrewCarluccio After digging into this, it is the osc.ts -> processData -> listCleared method that is clearing out the selected callers.  Not sure what is calling listCleared as no Companion button was pushed from the time a user was selected and the time listCleared was sent.  I can fix the selectedCaller so it stays after re-populating the list but wanted to check if there is anything more that needs to be done in the listCleared as ZoomOSC has been moving away from targetId.

**Comment by digitaldrummerj** [comment]
@JeffreyDavidsz @AndrewCarluccio checking if you have any feedback on this

**Comment by JeffreyDavidsz** [comment]
I did not have time to check it yet, but might have some time next week

**Comment by digitaldrummerj** [comment]
@AndrewCarluccio or @JeffreyDavidsz any feedback on this?  I would like to get this fixed as part of the v3 release.

**Comment by JeffreyDavidsz** [comment]
Not really I thought this wasn't an issue anymore, do you still experience this?

**Comment by digitaldrummerj** [comment]
@JeffreyDavidsz yes I still randomly experience it
