### ISSUE TITLE
Feature request: Have access to all ZoomOSC 4.2 OSC outputs as variables in Companion

### ISSUE THREAD

**Issue by MauriceD1999** [bitfocus/companion-module-zoom-osc-iso#121]
In the current documentation of ZoomOSC there is a list of OSC Outputs (page 20 to 22 in the ZoomOSC 4.2 syntax manual). Would it be possible to add these outputs as variables in the companion module (in the best case for all participants, at least for the user "me") - i am currently trying to implement the usage of the ZoomOSC companion module in an interactive StreamDeck Zoom control surface and would like to use these variables as feedback for styling my buttons according to the current state of audio, video and screen share. 

As far as I could test, this feature was present in the old ZoomOSC Companion module ([https://github.com/bitfocus/companion-module-liminalet-zoomosc](https://github.com/bitfocus/companion-module-liminalet-zoomosc)) with the 2.4.2 version of Companion - would it be possible to transfer it to the new module?

with best regards
Maurice

**Comment by digitaldrummerj** [comment]
The latest beta for v3 does have participant feedback for video on/off, mic on/off, is active speaker, and hand raised/lowered either individually or with advanced feedback that shows multiple states on the participant button.  I am not seeing an option on the ZoomOSC manual for screen share status.
