### ISSUE TITLE
Feature Request: Name of selected participant from ZoomISO output as variable

### ISSUE THREAD

**Issue by JaaHann** [bitfocus/companion-module-zoom-osc-iso#147]
Hey,

I would like to access the name of the selected participant of a ZoomISO output in participant mode as a variable in Companion to check who's assigned to which output.
I was very confused to realize this being not a default feature.

I case this might be impossible due to restricted data that ZoomISO provides, please let me know and I'll try my best to convince someone at ZoomISO... :)

For my workflow this would be an essential element and very nice to have.

Kind regards,
Jan

**Comment by digitaldrummerj** [comment]
Currently ZoomISO is not returning the participant name as part of the messages.  There is a spot where it is supposed to be but that spot is always blank.  I have reported this to the ZoomISO team.
