### ISSUE TITLE
Variable Audio Output Overwrites Video Output 

### ISSUE THREAD

**Issue by Hybrikon** [bitfocus/companion-module-zoom-osc-iso#160]
I want to use the video output names for my buttons. Zoom:Output1name doesn't show the name of the first video output, it shows the name of the first audio output. But Zoom:Output1resolution shows the resolution of the first video output

**Comment by digitaldrummerj** [comment]
I believe this is a dup of #147 

I'm.my testing of v3 Companion and latest ZoomISO the video selection name is not populated.

**Comment by digitaldrummerj** [comment]
this should be fixed in the latest release.
