### ISSUE TITLE
Feedback request – Spotlit

### ISSUE THREAD

**Issue by mbialystock** [bitfocus/companion-module-zoom-osc-iso#165]
Hello,

I'm looking for an additional feedback state that indicates when a participant is currently spotlit.

I would imagine a feedback state for when a participant is currently pinned would also be helpful. 

Is this possible?

**Comment by digitaldrummerj** [comment]
The Companion 3.1 beta has an auto populated spotlight group and an additional participant feedback state for spotlight on/off.  The presets have also been updated for this.

**Comment by mbialystock** [comment]
@digitaldrummerj Thanks so much for the heads up, I really appreciate it.
