### ISSUE TITLE
Zoom OSC / ISO Module Variable 'Call Status' not updating

### ISSUE THREAD

**Issue by sootysax** [bitfocus/companion-module-zoom-osc-iso#168]
The variable $(ZoomISO_PRODUCTION:callStatus) in the Zoom OSC / ISO module is not updating in real time.   The correct variable 'In Meeting' or 'offline' will be set when starting the module, but will not update if the client joins or leaves a meeting.
The only way to update the variable is to disable and re-enable the module (or quit and restart companion)

**Comment by digitaldrummerj** [comment]
I have emailed support and let them know that at least ZoomOSC on a Mac is not sending meeting status.
