### ISSUE TITLE
Participant buttons show the code rather than the name/result

### ISSUE THREAD

**Issue by alaninbelfast** [bitfocus/companion-module-zoom-osc-iso#169]
Previously, the Participant button text string was set to 

\n1. $(OSC___ISO_module:GalleryPosition01)

and would display the number and the name on the botton. However, there's been a change and the button text string now tries to only display the first 50 characters of the name and it's no longer parsing the function and is instead displaying the whole function. This is true for *every* button in the **Select From Participants** folder.
  
`1. ${substr($(OSC___ISO_module:Participant001),0,50)}`

Photo of behaviour attached.

The workaround is to manually edit every button text string ... but that's even more painful than pulling the buttons into place in the first place!

Same problem with the Select Group 2 Participants and other participant buttons.

![Screenshot 2024-01-31 at 15 59 05 (2)](https://github.com/bitfocus/companion-module-zoom-osc-iso/assets/113678371/13c05e15-1dc8-41fc-b8dd-15dbbfde61a9)

**Comment by alaninbelfast** [comment]
Sorry - should have mentioned that - Companion 3.2.0

**Comment by digitaldrummerj** [comment]
I do not currently have Companion 3.2.0 installed.  I do know that it works fine with Companion 3.1.0.  

If you click on the blue A button that I mentioned does it work for you to see the attendee name instead of the expression?

**Comment by digitaldrummerj** [comment]
glad we got a workaround for you while I investigate why the presets are not making it check by default like it used to.

**Comment by alaninbelfast** [comment]
This afternoon's Zoom wrangling has suddenly become much more manageable! ZoomOSC via Companion is such a great tool.

**Comment by digitaldrummerj** [comment]
I have run many events using the combo.  Being able to auto-track the host group, the gallery, the participant list, and custom groups makes it so much more manageable.

**Comment by alaninbelfast** [comment]
One row for speakers/panellists, another for audience members about to be asked to come on screen to ask questions - so much slicker than bothering with the gymnastics required to make Zoom Webinar a smooth experience!

**Comment by digitaldrummerj** [comment]
@alaninbelfast  this should be fixed in the latest Companion beta release.  It is something that broke within Companion.
