### ISSUE TITLE
join with ZAK, can't use variable for ZAK

### ISSUE THREAD

**Issue by roverradio** [bitfocus/companion-module-zoom-osc-iso#179]
I want to join with ZAK, but I am getting the ZAK token from an http call. The module doesn't seem to allow setting the value of ZAK with an internal variable when using Join a Metting with ZAK.

Would be fantastic if I could use a variable there.

Am I overlooking something?

**Comment by digitaldrummerj** [comment]
@roverradio Please check Pull Request #181 and let me know if it works for you.  I unfortunately currently do not have any way to test using ZAK tokens.
