### ISSUE TITLE
Start Screen Share & List Camera

### ISSUE THREAD

**Issue by shermanp** [bitfocus/companion-module-zoom-osc-iso#19]
Trying to use StartCameraShare from the pre-built buttons in companion. I get an error about out of index range in ZoomISO.

It seems like I should call for ListCameraDevices (which I cant find in the zoomISO module so I used genericOSC) to build the list index then select from that index. I was able to see the camera list index in the log but then I ran /StartCameraShare 6 and ISO crashed.

The crash seems to be a ISO issue. But wanted to report that the module might need a List Camera option (or easier to find if it is there)

**Comment by JeffreyDavidsz** [comment]
Hi @shermanp the StartCameraShare has a me now, so no index. It is possible to cycle through camera's: 'Cycle Shared Camera To Next Available'.
