### ISSUE TITLE
Auto Populated Group 1 Host/Co-host Should Not Be Able to Be Cleared 

### ISSUE THREAD

**Issue by digitaldrummerj** [bitfocus/companion-module-zoom-osc-iso#25]
There is a preset button that allows you to clear out the host/co-host group but there is no quick way to re-populate the group with the host/co-host.  Either we should not allow group 1 to be cleared out or have a preset to re-populate that group.

**Comment by JeffreyDavidsz** [comment]
I've disabled the clear preset and make/add presets for the first group. Power users are allowed to still do this by manually make the actions.

**Comment by digitaldrummerj** [comment]
> I've disabled the clear preset and make/add presets for the first group. Power users are allowed to still do this by manually make the actions.

If it does get cleared, is there a way to automatically repopulated it without having restart the module’s connection?

**Comment by JeffreyDavidsz** [comment]
Every time a list command is returned Companion will check if the participant is a host and add to the group (is not already there).

**Comment by digitaldrummerj** [comment]
Perfect.  Thank you
