### ISSUE TITLE
Change the participant preset buttons to have font set to auto size

### ISSUE THREAD

**Issue by digitaldrummerj** [bitfocus/companion-module-zoom-osc-iso#26]
Right now the participant preset buttons are set to 14pt font, but this causes longer user names to not display the whole name.  Any preset that is a participant preset (participant, group, gallery, etc) whould be set to auto for the font size.

**Comment by JeffreyDavidsz** [comment]
@AndrewCarluccio How do you feel about this, for me using 1 font size makes it easier to find the participants, but thats just my OCD I guess?

**Comment by digitaldrummerj** [comment]
The problem for me is that many times it cuts off the full name making it harder to make sure you have the right person

**Comment by digitaldrummerj** [comment]
here is an example of what I am talking about.  These are 4 different attendees but with 14 pt font, I can't tell which attendee it actually is.

![image](https://user-images.githubusercontent.com/708423/216801377-ed06e993-574c-47cf-8aaa-2b6a48a3bf40.png)

**Comment by AndrewCarluccio** [comment]
Ultimately I think the content must take precedent over the style in our preset to help with the initial onboarding UX, and the user can decide to change the style to increase readability as they become more comfortable with Companion. So I support the proposed change.

**Comment by JeffreyDavidsz** [comment]
That's cool @digitaldrummerj would you care to make a PR for this? Just change the fixed sizing to 'auto' for the selection presets (index, gallery and group)

**Comment by digitaldrummerj** [comment]
> That's cool @digitaldrummerj would you care to make a PR for this? Just change the fixed sizing to 'auto' for the selection presets (index, gallery and group)

Yes
