### ISSUE TITLE
Spotlight issue

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion-module-zoom-osc-iso#28]
Regarding Spotlight
Spotlight Panelist 1 does so
Add Spotlight on Panelist 2 does so
Selecting Panelist 2 and pressing "Un Spotlight" has no affect, and logs indicate "Error: message not handled"
"Toggle Spotlight" appears to add Spotlight of selected panelist, but does not remove Spotlight of selected panelist. Logs indicate "Error: message not handled" when the selected panelist is already Spotlighted
"Clear Spotlight" successfully removed all Spotlights.

**Comment by digitaldrummerj** [comment]
@JeffreyDavidsz did you mean to add the label wontfix to this?

**Comment by JeffreyDavidsz** [comment]
Yes the issue is with ZoomSDK not companion, when the SDK is fixed this will work

**Comment by clafarge** [comment]
Using ZoomOSC 4.1.2 (2023.02.03.17.37) and Companion Build 5640 for Mac on Apple Silicone, this appears to be resolved, @JeffreyDavidsz  and @digitaldrummerj
