### ISSUE TITLE
Toggle pin

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion-module-zoom-osc-iso#29]
Toggle Video does what I expect it to do, but Toggle Pin does not... I recall hearing that Toggle Pin might cause confusion… any clarity to offer here?

**Comment by clafarge** [comment]
Toggle Pin at that time would add a Pin for a Panelist who was not Pinned, but did not remove Pin status if they were Pinned.

**Comment by clafarge** [comment]
At this time, Toggle Pin appears to not send an associated ZoomID, @JeffreyDavidsz 

If _any_ panelist is currently Pinned and Toggle Pin is pressed, the command goes out as "/zoom/me/togglePin" and _no change_ is detected.

If _no_ panelist is pinned and Toggle Pin is pressed, the same command is seen in Log, and the current user (zISO panelist) is pinned.

**Comment by JeffreyDavidsz** [comment]
I see the me part is hard coded, so I'll change that to reflect (selected) users

**Comment by clafarge** [comment]
Using /zoom/zoomID/togglePin with one or more IDs fails as well as custom command
