### ISSUE TITLE
Raising hands feedback

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion-module-zoom-osc-iso#30]
After raising hands (manually for remote, as the OSC does not function, and using Companion for zOSC contributor), I then used Lower All Hands to... do that... the hands went down, but the hand images on buttons indicating raised hands in Companion remained. Clicking either of my 2 active Panelist selection buttons updated the state of both to remove Hand image.

**Comment by AndrewCarluccio** [comment]
it is possible that lowerAllHands does not send per-participant OSC feedback in ZoomOSC/ISO. You may have to assume the hands are lowered when you send the command from companion. The callback may not be triggered by Zoom SDK
