### ISSUE TITLE
Restore Group / Preset Interaction

### ISSUE THREAD

**Issue by AndrewCarluccio** [bitfocus/companion-module-zoom-osc-iso#35]
When the presets were re-organized, the automatic creation of preset categories for group index selection was removed (it's now all categorized under Manage Selections and Groups). The Manage category should keep all of the non-group-index buttons, but the index buttons should live inside of automatic preset categories for each additional group created. The Host Group should always be present and categorized into a Host Group preset folder.

**Comment by JeffreyDavidsz** [comment]
clear build that now
