### ISSUE TITLE
Make Host Group Persistent and Labeled 

### ISSUE THREAD

**Issue by AndrewCarluccio** [bitfocus/companion-module-zoom-osc-iso#36]
The Host Group (and preset) should always be available regardless of how many groups are selected in the module configuration. For example, if I only set 1 Group, I should have Host Group and Group 1. Host Group should be distinct from user-defined groups both by name and by disentanglement from index. It should have its own preset category. It should be clearly named, and divorced from user-defined groups.

**Comment by JeffreyDavidsz** [comment]
check, removed the option to make/add or clear the host group
