### ISSUE TITLE
Enable Original Sound (Not Functional)

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#39]
Companion Version 3.0.0 (3.0.0+5617-beta-627007a4)

OSC___ISO_module: Enable Original Sound not functioning. 

Testing included:

- Executing by referencing the Selected Participant
- Executed by typing in the participant name
- Tested on the host of the meeting

**Comment by JeffreyDavidsz** [comment]
Fix is already there in a later build

**Comment by ZoomTestKitchen** [comment]
> Fix is already there in a later build

I'm running today's build, **Companion v3.0.0+5619-beta-4be63095** and not having success with **Original Sound**.

Could you provide the build that contains this fix, then I'll just keep a look-out for it?

Also, I'm not familiar with the refresh cycle time from when you push to when it becomes available on the Companion download page. Is this a human process, therefore that timing may vary, based on person's availability? I realize that I may be pushing the timing boundaries here, if so, my apologies.

Thanks

**Comment by JeffreyDavidsz** [comment]
Hi Jeff, the cycle is each 6 hours or manually build. This fix should be there though. What does the log in OSC say? The original error was missing the selected participant. Please also test by entering me in the username leave blank if.... field. Just tested that, and it works for me.

**Comment by digitaldrummerj** [comment]
@ZoomTestKitchen you can see when Companion has updated the module reference at https://github.com/bitfocus/companion-bundled-modules/commits/main and looking for commit messages that say something like update zoom-osc-iso to v3.0.12.  

For the beta build, you can see the last time it was deployed by checking the last build time at https://github.com/bitfocus/companion/actions/workflows/nodejs.yml?query=branch%3Abeta

For the develop build, you can see the last time it was deployed by checking the last build time at https://github.com/bitfocus/companion/actions/workflows/nodejs.yml?query=branch%3Adevelop

By looking at the module reference update and the build times, you can determine if the latest module reference is in the latest installer or not.

**Comment by ZoomTestKitchen** [comment]
> @ZoomTestKitchen you can see when Companion has updated the module reference at https://github.com/bitfocus/companion-bundled-modules/commits/main and looking for commit messages that say something like update zoom-osc-iso to v3.0.12.
> 
> For the beta build, you can see the last time it was deployed by checking the last build time at https://github.com/bitfocus/companion/actions/workflows/nodejs.yml?query=branch%3Abeta
> 
> For the develop build, you can see the last time it was deployed by checking the last build time at https://github.com/bitfocus/companion/actions/workflows/nodejs.yml?query=branch%3Adevelop
> 
> By looking at the module reference update and the build times, you can determine if the latest module reference is in the latest installer or not.

Super helpful guidance as I'm getting more familiar with GitHub. Thanks

**Comment by ZoomTestKitchen** [comment]
> Hi Jeff, the cycle is each 6 hours or manually build. This fix should be there though. What does the log in OSC say? The original error was missing the selected participant. Please also test by entering me in the username leave blank if.... field. Just tested that, and it works for me.

@JeffreyDavidsz 

It appears that Enable Original Sound ON/OFF works for ME, as well as a Selected Participant, although the screen does not reflect the change until I force a screen refresh by switching from Speaker View to Gallery View or vice-versa.

Attaching two screen recordings to show this behavior.

Here is what the ZoomOSC log is showing.

```
Info: received message /zoom/zoomID/enableOriginalSound 16780288
 Verbose: message address is --/zoom/zoomID/enableOriginalSound--
 Verbose: message arguments are --(
    16780288
)--
 Verbose: message type tags are --,i--
 Verbose: Got userID from zoomID
 Verbose: acting on user 0 with arguments (
)
 Info: Enabled original sound

```

```
Verbose: message type tags are --,--
 Info: received message /zoom/zoomID/disableOriginalSound 16780288
 Verbose: message address is --/zoom/zoomID/disableOriginalSound--
 Verbose: message arguments are --(
    16780288
)--
 Verbose: message type tags are --,i--
 Verbose: Got userID from zoomID
 Verbose: acting on user 0 with arguments (
)
 Info: Disabled original sound

```


https://user-images.githubusercontent.com/124208331/216496588-ad0faa85-7ccd-4c97-9b44-19965fdb8e30.mp4


https://user-images.githubusercontent.com/124208331/216496613-68f12e5d-3d24-4e50-b772-3ed90d36cc13.mp4

**Comment by JeffreyDavidsz** [comment]
Ok thanks for this. This tells me Companion is sending the right stuff and gets confirmation but the GUI of Zoom doesn't update. I'll close this and forward it to the Zoom team

**Comment by ZoomTestKitchen** [comment]
Question regarding **Original Sound**.

Why is the **`username (keep blank when you pre-select)`** provided for **Original Sound**, when it is not for **Name Labels**, **Non Video Users**, **Allow Unmute**, and **Waiting Room**?  It implies that we would/could remotely enable/disable original sound on remote systems, but not for **Name Labels**, **Non Video Users**, **Allow Unmute**, and **Waiting Room**?

**Comment by JeffreyDavidsz** [comment]
Need a bit of help here;
Name labels?
Non video Users?
Allow Unmute?
Waiting Room?
I cannot find those actions?

**Comment by ZoomTestKitchen** [comment]
Sorry about that... I just used general references. Here are the actual actions names.

**Name labels?**

> OSC___ISO_module: Show User Names On Video

**Non video Users?**

> OSC___ISO_module: Show Non Video Participants

**Allow Unmute?**

> OSC___ISO_module: Enable Users To Unmute

**Waiting Room?**

> OSC___ISO_module: Enable Waiting Room

**Comment by JeffreyDavidsz** [comment]
These are global actions meaning they are for all users. It will ignore your selection
