### ISSUE TITLE
Indexed Based Feedback

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#40]
Consider updating **Indexed based feedback** to **Participant based feedback**.

The descriptions below are up-to-date with the new naming conventions, where "index" appears to need to be updated, as well.

- in a group feedback | Position 1 - 999
- gallery based feedback | Position 1 - 49
- username based feedback | type in username

**Comment by JeffreyDavidsz** [comment]
@ZoomTestKitchen I've changed the descriptions as per suggested
