### ISSUE TITLE
Unresolved Variable Values

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#42]
Use-Case Description:

A dedicated button on the Stream Deck that actively displays `$(OSC___ISO_module:activeSpeaker)`. One example could be, if that Active Speaker is disruptive and needs to be quickly muted, or ejected, or as simple as wanting to quickly Spotlight them, or add them to a group. 

Right now it is not possible because the variable that is being referenced is getting passed through as a literal string versus its resolved value.

What's being passed is wrapped in quotes:  `/zoom/userName/mute "$(OSC___ISO_module:activeSpeaker)". So, although we can dynamically display the Active Speaker, we can't act upon it dynamically.

This same challenge is present when trying to reference these variables in a Companion Trigger.

Would it be possible to pass a string, if it is a string, and an integer if it is an integer. This would provide a ton more flexibility for advanced users?

**Comment by AndrewCarluccio** [comment]
@JeffreyDavidsz was there a regression in being able to pass variable names as arguments in Companion itself? I remember previously I had tried doing /zoom/userName/sendToBreakout "$(OSC___ISO_module:activeSpeaker)" or something similar and was successful, so I am surprised this doesn't already work. Was there a change?

**Comment by JeffreyDavidsz** [comment]
For Companion v3 the complete module was rewritten, also parsing of variables is different from v2. This means I probably messed up that part, missing a dot somewhere. I see a pull request coming in with the fix. I'll check that and merge

**Comment by ZoomTestKitchen** [comment]
Can you guys help me understand what causes an Issue to close? Does it mean that it has been completed and we can expect to see it in an upcoming release, or does it close here and move-on someplace else? Thanks

**Comment by JeffreyDavidsz** [comment]
An issue can close by accepting a pull request that has the reference as a fix for the issue. Also manually. Normally there will be a comment about that. In this case someone made a fix for the solution and by merging it will close automatically. Unfortunately the fix is partly working so there needs to be done more. I'll reopen the issue. Regarding when will this be included in a build that's up to the maintainers of Companion. The normal route is via slack by mention that code has been altered and the module can be updated. In this case as im one of the maintainers im on this module and update regularly.

**Comment by digitaldrummerj** [comment]
@JeffreyDavidsz can you let me know what isn’t working in the PR so I can fix it?

**Comment by JeffreyDavidsz** [comment]
PR is working @digitaldrummerj , had an other issue on my system. Fixed now. I've included your lint PR, thanks for that. There will be a point where I'll open up the module, so you can update it when needed, but for now its stricted untill we have a good build that everyone is happy with

**Comment by ZoomTestKitchen** [comment]
> An issue can close by accepting a pull request that has the reference as a fix for the issue. Also manually. Normally there will be a comment about that. In this case someone made a fix for the solution and by merging it will close automatically. Unfortunately the fix is partly working so there needs to be done more. I'll reopen the issue. Regarding when will this be included in a build that's up to the maintainers of Companion. The normal route is via slack by mention that code has been altered and the module can be updated. In this case as im one of the maintainers im on this module and update regularly.

Thank you for the clarity.

**Comment by digitaldrummerj** [comment]
> PR is working @digitaldrummerj , had an other issue on my system. Fixed now. I've included your lint PR, thanks for that. There will be a point where I'll open up the module, so you can update it when needed, but for now its stricted untill we have a good build that everyone is happy with

I am good with having to submit pull request for changes.  I believe it is always good to get another set of eyes to look at the code changes and test them before merging the code.
