### ISSUE TITLE
Companion version 3.0.0+5627 does not receive ZoomOSC data feed.

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#45]
After updating my Companion from 3.0.0+5619 to 3.0.0+5627 I no longer could receive data in ZoomOSC. I restarted ZoomOSC, Companion, and my M1 Mac with no improvement. I finally quit 5627 and launched 5619 and the data-stream returned. There was another person in the meeting running version 3.0.0+5624 and was receiving data successfully.

Not sure who owns this issue, but wanted to get it in the system.

**Comment by digitaldrummerj** [comment]
@ZoomTestKitchen can you test the latest beta 3.0.0+5629-beta and see if you have the same issue?

**Comment by ZoomTestKitchen** [comment]
I will be able to test this later, today.

**Comment by JeffreyDavidsz** [comment]
Any updates?

**Comment by ZoomTestKitchen** [comment]
I download the latest beta every day or two. I haven't seen this behavior again.

**Comment by JeffreyDavidsz** [comment]
Check I'll close this
