### ISSUE TITLE
Participant Names not refreshing

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#46]
When an attendee changed their profile name while in the meeting, that new name was quickly reflected in GalleryPosition01, for example, and also accurately updated in ParticipantPosition, but I had her as a member of Group 2, and the name change was not refreshed/updated until I removed her and re-added to the group.

I appears that there is not a polling refresh interval on names of attendees within a Group.

**Comment by JeffreyDavidsz** [comment]
When renaming no update on the group was applied. fixed this in latest commit (not a build yet), closing this
