### ISSUE TITLE
OSC / ISO module: Rename function unexpected results

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#49]
Companion Version 2.4.2 (2.4.2+4911-v2-4.2-fcb5a863)

OSC / ISO module: Rename
username: <blank> pre-selected participant
Name: $(internal:custom_RenameValue)

Attempting to rename a participant using a custom variable **$(internal:custom_RenameValue)** 

When executing the rename function it sets the name value to $(internal:custom_RenameValue)

As a result, when displayed by referencing Gallery Position #1 it actually resolves to the variables value "Jeff"

When displayed by referencing Participant ID it resolves to the variable value "Jeff"

Inside of Zoom in the participants list and name label in the gallery it displays $(internal:custom_RenameValue)

I'm not sure that if what you're currently working on regarding passing variables will fix this or not, but wanted to make sure it was submitted for visibility.

**Comment by digitaldrummerj** [comment]
Same variable fix would need to be applied for rename to be able to use a variable in the rename.

For the button text update, I believe @JeffreyDavidsz  is working on the fix to update the buttons when a person is renamed in Zoom.
