### ISSUE TITLE
Selected Panelist Forgotten...

### ISSUE THREAD

**Issue by clafarge** [bitfocus/companion-module-zoom-osc-iso#52]
@JeffreyDavidsz 
There appears to be some housekeeping that's making Companion forget currently-selected Panelist... after a few toggleSpotlights on one selected user, I left it sitting for about a minute until Ping/Pong and gallery-oriented events came through and apparently cleared Companion of selection, although the Panelist still has highlight on Stream Deck key.

16:44:50.799 - Info: sending OSC message /zoomosc/user/spotlightOn -1 "Chad LaFarge" -1 16778240
 16:44:51.464 - Info: received message /zoom/zoomID/toggleSpot 16778240
 16:44:51.477 - Info: un spot lit user
 16:44:52.049 - Info: got spotlight change - users now (null)
 16:44:52.050 - Info: sending OSC message /zoomosc/user/spotlightOff -1 "Chad LaFarge" -1 16778240
 16:46:07.090 - Info: received message /zoom/zoomID/toggleSpot 16778240
 16:46:07.093 - Info: spotlit user
 16:46:07.647 - Info: got spotlight change - users now (
    16778240
)
 16:46:07.648 - Info: sending OSC message /zoomosc/user/spotlightOn -1 "Chad LaFarge" -1 16778240
 16:46:21.921 - Info: received message /zoom/zoomID/toggleSpot 16778240
 16:46:21.933 - Info: un spot lit user
 16:46:22.500 - Info: got spotlight change - users now (null)
 **16:46:22.501 - Info: sending OSC message /zoomosc/user/spotlightOff -1 "Chad LaFarge" -1 16778240**
 **16:47:29.442 - Info: received message /zoom/ping**
 16:47:29.443 - Info: sending OSC message /zoomosc/pong 0 "ZOSC_4.1.2_MAC" 2 1 1 0 3 1
 16:47:29.449 - Info: received message /zoom/subscribe 2
 16:47:29.450 - Info: sending OSC message /zoomosc/me/list -1 "zOSC Chad" -1 16796672 0 3 2 1 1 0 0
 16:47:29.450 - Info: sending OSC message /zoomosc/user/list -1 "Chad LaFarge" -1 16778240 0 3 1 1 1 0 0
 16:47:29.451 - Info: sending OSC message /zoomosc/user/list -1 "Chad LaFarge | Columbia, MO | 1050" -1 16795648 0 3 3 1 1 0 0
 16:47:29.451 - Info: sending OSC message /zoomosc/listCleared
 16:47:29.455 - Info: sending OSC message /zoomosc/me/list -1 "zOSC Chad" -1 16796672 0 3 2 1 1 0 0
 16:47:29.455 - Info: sending OSC message /zoomosc/user/list -1 "Chad LaFarge" -1 16778240 0 3 1 1 1 0 0
 16:47:29.456 - Info: sending OSC message /zoomosc/user/list -1 "Chad LaFarge | Columbia, MO | 1050" -1 16795648 0 3 3 1 1 0 0
 16:47:29.456 - Info: sending OSC message /zoomosc/galleryOrder
 16:47:29.456 - Info: sending OSC message /zoomosc/galleryCount 0
 16:47:29.457 - Info: sending OSC message /zoomosc/galleryShape 0 0
 16:47:29.457 - Info: received message /zoom/galTrackMode 1
 Info: gallery tracking mode changed to 1
 16:47:29.457 - Info: sending OSC message /zoomosc/galleryOrder
 16:49:29.458 - Info: received message /zoom/subscribe 2
 16:49:29.459 - Info: sending OSC message /zoomosc/me/list -1 "zOSC Chad" -1 16796672 0 3 2 1 1 0 0
 16:49:29.463 - Info: sending OSC message /zoomosc/user/list -1 "Chad LaFarge" -1 16778240 0 3 1 1 1 0 0
 16:49:29.463 - Info: sending OSC message /zoomosc/user/list -1 "Chad LaFarge | Columbia, MO | 1050" -1 16795648 0 3 3 1 1 0 0
 16:49:29.464 - Info: sending OSC message /zoomosc/listCleared
 16:49:29.464 - Info: sending OSC message /zoomosc/me/list -1 "zOSC Chad" -1 16796672 0 3 2 1 1 0 0
 16:49:29.464 - Info: sending OSC message /zoomosc/user/list -1 "Chad LaFarge" -1 16778240 0 3 1 1 1 0 0
 16:49:29.465 - Info: sending OSC message /zoomosc/user/list -1 "Chad LaFarge | Columbia, MO | 1050" -1 16795648 0 3 3 1 1 0 0
 16:49:29.465 - Info: sending OSC message /zoomosc/galleryOrder
 16:49:29.466 - Info: sending OSC message /zoomosc/galleryCount 0
 16:49:29.466 - Info: sending OSC message /zoomosc/galleryShape 0 0
 16:49:29.467 - Info: received message /zoom/galTrackMode 1
 Info: gallery tracking mode changed to 1
 16:49:29.467 - Info: sending OSC message /zoomosc/galleryOrder
 16:49:29.471 - Info: sending OSC message /zoomosc/galleryCount 0
 **16:50:02.624 - Info: received message /zoom/zoomID/toggleSpot
 16:50:02.625 - Error: message not handled** 

Notable marks are Bold.

At this time, my Stream Deck continues to tell me that "Chad LaFarge" is selected, but toggleSpotlight, and other commands that would send selected ZoomId have no ZoomId.

**Comment by JeffreyDavidsz** [comment]
Need to test this a bit more, for me after the ping/pong I'm still able to mute/unmute
