### ISSUE TITLE
Naming Inconsistency - is it Participant###, Position###, or Index###

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#53]
Examples below represent the question: Is it Participant ###, Position ###, or Index ###

I believe that the use of "Participant" and "Participant Position" across the board, and getting rid of the use of "index", "participant index"

### Section - **Button Text String**

>// Referred to as **Participant** //

>> **Button text string:** $(OSC___ISO_module:**Participant###**)

### Section - **Press Actions**

>// Referred to as **Participant Index** //

>> **Action:** OSC___ISO_module: Preselect user by **Participant Index**
Proposed Change: _**`OSC___ISO_module: Preselect user by Participant Position`**_

>**Press Actions - Position**
>>// Referred to as **Position** in the label //
>>// Referred to as **Participant ##** in the dropdown list //

### Section - **Feedbacks**

>// Referred to as **Participant index based feedback** //

>> **Feedback:** OSC___ISO_module: **Participant** index based feedback
Proposed Change: _**`OSC___ISO_module: Participant Position feedback`**_

>Dropdown List Label = **Index**
Proposed Change: _**`Participant Position`**_

>>**Dropdown List Choices:** **Position ###**

![Screenshot 2023-02-06 at 3 39 19 PM](https://user-images.githubusercontent.com/124208331/217101478-4b614073-a213-4257-ab83-81fa7459363d.png)
![Screenshot 2023-02-06 at 3 39 41 PM](https://user-images.githubusercontent.com/124208331/217101505-06bc55db-db6f-4f75-9663-02b1e5415bfb.png)

**Comment by JeffreyDavidsz** [comment]
Thanks for this!

**Comment by ZoomTestKitchen** [comment]
I just looked at these updates. This is clean. Thanks for the quick turn-around.
