### ISSUE TITLE
create an error message for multiple participants when only one is allowed

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion-module-zoom-osc-iso#54]
at this time, using ZoomOSC 4.1.2 (2023.02.03.17.37) and Companion Build 5640 for Mac on Apple Silicone, having multiple Panelists selected and pressing "Pin" sends the command:
/zoom/zoomID/pin 16794624
… which is the zoomID of the second panelist selected. As pin is meant as single-panelist command, if multiple are provided, would it be possible to indicate error? 

If using custom command to send multiple IDs, it responds in Log with "Error: message not handled"

Source Zoom Chad Lafarce

**Comment by JeffreyDavidsz** [comment]
[clafarge](https://github.com/clafarge)

**Comment by ZoomTestKitchen** [comment]
> at this time, using ZoomOSC 4.1.2 (2023.02.03.17.37) and Companion Build 5640 for Mac on Apple Silicone, having multiple Panelists selected and pressing "Pin" sends the command: /zoom/zoomID/pin 16794624 … which is the zoomID of the second panelist selected. As pin is meant as single-panelist command, if multiple are provided, would it be possible to indicate error?
> 
> If using custom command to send multiple IDs, it responds in Log with "Error: message not handled"
> 
> Source Zoom Chad Lafarce

Jeffrey, when you state "As pin is meant as a single-panelist" is this statement clarifying what the command is designed to do, or that Zoom Pinning is designed a single, per user event? Zoom Pinning does support multi-pinning, up to 9 local pins. Just checking for clarity. Thanks

**Comment by JeffreyDavidsz** [comment]
Hi @ZoomTestKitchen the source of the text is from Chad (tester @ Zoom). I've just put it on Github because I need to keep track. That being said If I remember correctly the Pin command is for a single user and the addPin is for multiple. That is also how I programmed it in Companion. @AndrewCarluccio is this correct?

**Comment by AndrewCarluccio** [comment]
@JeffreyDavidsz you are correct
