### ISSUE TITLE
Consider Adding "Previous Selected List" functionality

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#57]
Adding a "Previous Selected List" option will provide a quick method to recall what was previously selected. Therefore, if we need to quickly go make a change to group membership, etc. we can just recall the previously selected list to get back where we were.

**Comment by ZoomTestKitchen** [comment]
@JeffreyDavidsz,

I see that **OSC___ISO_module: Restore Previous Selections** is in the 3.0.0+5659 build. Quick question: what triggers an update to the Previous Selected List?

Let's say I hit clear selections so I can quickly add somebody to a group. If I clear selections and then call Restore Previous Selections, I'm assuming the current selections will be populated with the previous list.

But, what shouldn't I do? Like if I manually Select somebody, can I still call Restore Previous Selections, or has it now been over-written? 

I'm just trying to understand what event causes the Previous Selections to be populated, so I can stay away from causing an event that might lose the previous list by my own doing.

Thanks

**Comment by JeffreyDavidsz** [comment]
I've tried to make it like an undo action. It should store every time you select or deselect a participant
