### ISSUE TITLE
When adding selected to a group it seems to automatically clear all selected

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#59]
When adding selected to a group it seems to automatically clear all selected.

This makes it challenging to add a group of selected to multiple groups, without having to go back and re-selecting them again.

Another example: I configured a trigger to watch for a hand-raise in Gallery Position #2. This represents the person who is almost on stage. When they arrive at Gallery Position #2 the trigger "Preselects" them, adds them to Group 2, then sends them a Chat message letting them know to turn their camera on. Unfortunately, the Chat message fails because there is nobody preselected. This is actually because Add to Group 2 took place before sending the Chat message, therefore the preselect list is now empty.

I realize I can change the order of execution, but I feel that this is a behavior we should control.

Can we remove this behavior, and leave it to us to either add a Clear Selected after adding, or not?

**Comment by JeffreyDavidsz** [comment]
Closing this as it relates to other issues
