### ISSUE TITLE
Mute All behavior unexpected

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#60]
When executing **Mute-All** it muted everybody in the meeting (attendees, hosts, co-hosts) except the ZoomISO machine itself, which was a co-host.

I would hope for it to mute all attendees, and NOT the Host and Co-Hosts. This would be my vote for its built-in behavior.

A note regarding **Mute-All Except**

My vote for this behavior would be to Mute all attendees, except those that have been pre-selected. And do not mute the host and co-hosts.

**Comment by JeffreyDavidsz** [comment]
First one is for Zoom to address. Second one sends the participants you have selected to Zoom, they should not be muted then. But after that is to Zoom how they respond. I would suggest to put it there. Nothing we can do from here
