### ISSUE TITLE
Gallery Page Next/Previous

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#61]
Companion 2.4.1+4898-v2.4.1-9646192a

I'm in a meeting with about 650 attendees. On my Companion page I'm displaying GalleryPosition01-25. In my ZoomISO client I'm displaying 25 participants per page. When I execute Gallery Page Next, although the actual gallery in the client does page to the next set of attendees, the Companion page does not update to these new attendees that are now occupying GalleryPosition01-25.

Should I be expecting this behavior of paging with updates on the Companion Page?

**Comment by JeffreyDavidsz** [comment]
This was a known issue. SDK did not respond back the gallery order. As I recall this had been fixed. Might be a manual fix by me in Companion (2.4.2 or 3.0.0) or the ZoomOSC ZoomISO client.
I know it's working now, so I'll close this.

**Comment by AndrewCarluccio** [comment]
@JeffreyDavidsz @ZoomTestKitchen there's a known issue where pagination did not call a callback in the SDK required for gallery order information. @JeffreyDavidsz were you sending manual pings in previous versions to get this?

**Comment by AndrewCarluccio** [comment]
That's fine, just be aware that the fix for the Liminal Apps won't be shipping to customers for a while
