### ISSUE TITLE
Windows 10 High CPU Usage with ZoomISO

### ISSUE THREAD

**Issue by digitaldrummerj** [bitfocus/companion-module-zoom-osc-iso#63]
I am seeing Companion CPU usage on Windows 10 go from around 1% to 35% to 40% by just turning on the ZoomOSC/ISO module with a connection to my ZoomISO Pro Mac Mini M2 machine.  If I turn off the ZoomOSC/ISO connection, the Companion CPU  goes back to around 1%.  I am not connected to a meeting and I do not have any buttons configured in Companion.

I am running Companion v3.1.0+5668-develop-12371c54

Update Speed: 

* Fast -> up to 35% CPU
* Medium -> up to 11%
* Slow -> up to 6%
* Extra Slow -> up to 4%

**Comment by JeffreyDavidsz** [comment]
@digitaldrummerj how is the module doing at the moment for you?

**Comment by digitaldrummerj** [comment]
Appears to be fixed for not being in a meeting.  I will test again when the zISO room in After Hours come back on the 17th.

**Comment by AndrewCarluccio** [comment]
@digitaldrummerj is this still an issue? Could be a companion build issue vs a module issue

**Comment by JeffreyDavidsz** [comment]
Thanks
