### ISSUE TITLE
Feedback - Type of Feedback "Camera Live" needs to be "Camera Off"

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#65]
Companion Version 3.0.0+5661-beta-b166e95e

> OSC___ISO_module: Gallery based feedback
> OSC___ISO_module: Participant position based feedback
> OSC___ISO_module: Group based feedback

>Type of feedback dropdown list option: "Camera Live"

This event actually triggers when the Camera is OFF.

Can we change "Camera Live" to "Camera Off"?

**Comment by JeffreyDavidsz** [comment]
The Commit 30f0409 solved the issue
