### ISSUE TITLE
OSC___ISO_module: Restore Previous Selections not working

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#66]
Companion Version 3.0.0+5663-beta-79f2fb18

This is my Trigger:

**Events:**
> On Condition Becoming True

**Condition:**
> OSC___ISO_module: Gallery based feedback | **Gallery Position 2** | Type of Feedback: **Hand Raised**

**Actions:**
> OSC___ISO_module: Preselect user by Gallery Position | Position: **Position 2** | Option: **Select**
> OSC___ISO_module: Add selection to group | Group: **Group** 2 | Add or set: **Add**
> OSC___ISO_module: Restore Previous Selections: | **Nothing to configure**

I have other Actions that I need to execute after these but cannot because there are no pre-selected items from the restore function. I've inserted 2000ms delays between each Action to see the results clearly.

**Comment by JeffreyDavidsz** [comment]
Closing this, related to other issues
