### ISSUE TITLE
Group 0 - Hosts Group not available in dropdown list

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#67]
Companion Version: 3.0.0+5663-beta-79f2fb18

**Actions**:
> OSC___ISO_module: Preselect user by group Position | **Group Dropdown List**

When trying to reference by Group Position the Hosts Group is not a selectable choice in the dropdown list. I realize that we can't add/remove from the Hosts Group, but it is necessary to be able to pre-select Hosts for spotlighting, etc.

**Comment by JeffreyDavidsz** [comment]
I'm actually seeing this, so this might be a version issue. I'll close this. Please report back when after today's version, you still have the issue
(url)
<img width="475" alt="Host group" src="https://user-images.githubusercontent.com/40557816/224495141-e7da209d-543d-4f97-9619-bfac13d3cf7f.png">
