### ISSUE TITLE
selectedNumberOfCallers is empty after Chat Via DM

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#68]
Companion Version: 3.0.0+5666-beta-07c68547

After calling **OSC___ISO_module: Chat Via DM** the selectedNumberOfCallers is empty. This makes it impossible to execute any further actions that are dependent on selectedNumberOfCallers.

I've tried to restore the selections with the following **OSC___ISO_module: Restore Previous Selections** but it does not work.

**Comment by JeffreyDavidsz** [comment]
This should be fixed as it it linked to the other issue with selection
