### ISSUE TITLE
Overall Workflow seems designed for Single Action Only

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#69]
I like the designed workflow of Select, Optionally Add to Group, then execute Action on Selected or Group.

The unfortunate part of the design is that it doesn't support multiple actions on a single selection of attendees. Even when you select a Group and then execute an action, it clears the selection after most actions, therefore making it impossible to execute multiple actions on Selected, or Selected Group.

An example would be that I want to select 3 attendees, make them a member of a group, send them a DM, and then Spotlight them. Right now, this can't be accomplished due the Selected List gets cleared after the 1st Action.

Even simpler things like adding a selection to more than one group.

I'm really hoping that this can change.

**Comment by AndrewCarluccio** [comment]
This is a significant regression. I really don't want the module to automatically deselect after applying an action. To deselect, I would want users to have to explicitly add the deselect action.

**Comment by AndrewCarluccio** [comment]
@JeffreyDavidsz any updates on this one?

**Comment by JeffreyDavidsz** [comment]
Not yet haven't been able to program anything the last weeks, but it will be straightened soon

**Comment by JeffreyDavidsz** [comment]
After AddToGroup, RemoveToGroup, applyOutput(s), applyChannel, muteAllExceptHost & overall after each userCommand the selection now stays. I'll update the module after doing some other issues.
