### ISSUE TITLE
Toggle Spotlight Issue

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#70]
**Single Button Companion Definition**

- OSC___ISO_module: Preselect Group | Group 1
- OSC___ISO_module: Toggle Spotlight | [blank]
 
**Result**
- Toggle Spotlight (1st press) successfully spotlights all members of the group
- Toggle Spotlight (2nd press) only removes the spotlight of the first member of the group

**Expected Behavior**

Should be able to Select Group and Spotlight All members of selected Group. Note: this is an additive spotlight to existing spotlights
Should be able to Select Group and Remove All group member spotlights of Selected Group.

**Comment by JeffreyDavidsz** [comment]
@AndrewCarluccio This seems a Zoom thing? does toggle back only passes the first caller?

**Comment by AndrewCarluccio** [comment]
@JeffreyDavidsz probably an SDK issue. I will investigate but you can close it for companion's sake
