### ISSUE TITLE
SELECTED Feedback is being triggered by Active Mic

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#75]
On a Stream Deck page where **Feedback** is configured with **Selected**, the **Active Mic** is the cause for the trigger, although I believe Selected is also triggering it.

**Comment by AndrewCarluccio** [comment]
What is the top bottom orders of your feedbacks? Selected should be primary.

**Comment by ZoomTestKitchen** [comment]
On either Companion 5764 or 5765 this behavior stopped. 

The order of my feedbacks are:

- Camera Off
- Hand Raised
- Selected

When my mic was the Active Speaker, it would trigger the Selected feedback.

**Comment by JeffreyDavidsz** [comment]
@ZoomTestKitchen can you verify this has nothing to do with your triggers? I cannot replicate this behaviour. Active mic does not trigger selected feedback on my end.

**Comment by ZoomTestKitchen** [comment]
I'm now guessing that this audio triggering the selection is also due to a trigger I wrote. I am confirming this with another user and will report the results.

My apologies. I need to test the workflow of... Clear Selections, select what I need my trigger to select, UnSelect what my trigger selected, and then restore the previous selections.

I know that you added "**Restore Previous Selections**" but, I'm unfamiliar with when that restoration collection is created, and long it is retained, or what will overwrite it.

My apologies for these two tickets that were obviously my own issue.

**Comment by ZoomTestKitchen** [comment]
I’ve been able to confirm that this was also related to triggers, not a code issue.
