### ISSUE TITLE
OSC___ISO_module: Assign Participant To BreakoutRoom is missing a parameter

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#76]
`OSC___ISO_module: Assign Participant To BreakoutRoom` is missing a parameter that would designate which breakout room.

**../assignToBreakout {str breakout name | int breakout index}**

It currently only provides "single username (keep blank when you pre-select)

**Comment by AndrewCarluccio** [comment]
To be compliant, this command needs to either take the breakout index or the breakout name
