### ISSUE TITLE
makeCoHost twice, the 2nd time causes a Companion module error

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#77]
Here are the steps I take...

1. Select a participant that is not currently a co-host
2. Execute makeCoHost, everything is fine
3. Execute revokeCoHost, everything is fine
4. With the same selected participant
5. Execute makeCoHost (this is the 2nd time), the Companion modules generates errors and has to reset
6. 

Here is the Companion module log data...

debug: M1MacMini, user role 1
debug: Jeff Widgren | Overland Park, KS, user role 3
debug: Jeff Widgren | Overland Park, KS, user role 3
debug: vMix Laptop, user role 2
debug: vMix Laptop, user role 2
debug: MacbookPro, user role 2
debug: MacbookPro, user role 2
debug: iMacDesktop, user role 3
debug: iMacDesktop, user role 3
debug: iPad, user role 3
debug: iPad, user role 3
error: Module registration failed Error: Call timed out
    at t.IpcWrapper.sendWithCb (/Applications/__apps/Companion 3.0/Companion.app/Contents/Resources/bundled-modules/zoom-osc-iso/main.js:2:458803)
    at /Applications/__apps/Companion 3.0/Companion.app/Contents/Resources/bundled-modules/zoom-osc-iso/main.js:2:451884
Starting up module class: u
Sentry disabled
info: Welcome, Zoom module is being initialized
info: changing config!
info: Listening to ZoomOSC on port: 1234
debug: ZISO_2.0.6_pro_MAC Pro
debug: M1MacMini, user role 1
debug: M1MacMini, user role 1
debug: Jeff Widgren | Overland Park, KS, user role 3
debug: Jeff Widgren | Overland Park, KS, user role 3
debug: vMix Laptop, user role 2
debug: vMix Laptop, user role 2
debug: MacbookPro, user role 2
debug: MacbookPro, user role 2
debug: iMacDesktop, user role 3
debug: iMacDesktop, user role 3
debug: iPad, user role 3
debug: iPad, user role 3
debug: M1MacMini, user role 1
debug: M1MacMini, user role 1
debug: Jeff Widgren | Overland Park, KS, user role 3
debug: Jeff Widgren | Overland Park, KS, user role 3
debug: vMix Laptop, user role 2
debug: vMix Laptop, user role 2
debug: MacbookPro, user role 2
debug: MacbookPro, user role 2
debug: iMacDesktop, user role 3
debug: iMacDesktop, user role 3
debug: iPad, user role 3
debug: iPad, user role 3
error: Module registration failed Error: Call timed out
    at t.IpcWrapper.sendWithCb (/Applications/__apps/Companion 3.0/Companion.app/Contents/Resources/bundled-modules/zoom-osc-iso/main.js:2:458803)
    at /Applications/__apps/Companion 3.0/Companion.app/Contents/Resources/bundled-modules/zoom-osc-iso/main.js:2:451884
Starting up module class: u
Sentry disabled
Module-host accepted registration
info: Welcome, Zoom module is being initialized
info: changing config!
info: Listening to ZoomOSC on port: 1234
debug: ZISO_2.0.6_pro_MAC Pro
debug: M1MacMini, user role 1
debug: M1MacMini, user role 1
debug: Jeff Widgren | Overland Park, KS, user role 3
debug: Jeff Widgren | Overland Park, KS, user role 3
debug: vMix Laptop, user role 2
debug: vMix Laptop, user role 2
debug: MacbookPro, user role 2
debug: MacbookPro, user role 2
debug: iMacDesktop, user role 3
debug: iMacDesktop, user role 3
debug: iPad, user role 3
debug: iPad, user role 3
debug: M1MacMini, user role 1
debug: M1MacMini, user role 1
debug: Jeff Widgren | Overland Park, KS, user role 3
debug: Jeff Widgren | Overland Park, KS, user role 3
debug: vMix Laptop, user role 2
debug: vMix Laptop, user role 2
debug: MacbookPro, user role 2
debug: MacbookPro, user role 2
debug: iMacDesktop, user role 3
debug: iMacDesktop, user role 3
debug: iPad, user role 3
debug: iPad, user role 3

**Comment by AndrewCarluccio** [comment]
Confirming the build? Latest?

**Comment by ZoomTestKitchen** [comment]
ZoomISO Version 2.0.6 (2023.03.27.21.12)

Companion Version (3.0.0+5765-beta-6f1e5e4e)

**Comment by AndrewCarluccio** [comment]
@JeffreyDavidsz will investigate

**Comment by digitaldrummerj** [comment]
I had this same issue today.  I took a look at the ZoomGroupData[0] and found the issue.  When you remove a co-host, it makes the attendee position the ZoomGroupData[0] data structure null so that when it tries to do a .ZoomId null it is not able to do it.

Details:

Here is the error message that I got that gives a bit more details.  I am also running the code for the https://github.com/bitfocus/companion-module-zoom-osc-iso/pull/91 

ZoomOSC 4.2
Companion v3.0.0+5780-beta-bb541a1a

```
error: C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\dist\osc.js:297
                                const index = this.instance.ZoomGroupData[0].users.findIndex((id) => id.zoomID === zoomId);
                                                                                                        ^

TypeError: Cannot read properties of undefined (reading 'zoomID')
    at C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\dist\osc.js:297:105
    at Array.findIndex (<anonymous>)
    at OSC.processData (C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\dist\osc.js:297:84)
    at osc.UDPPort.<anonymous> (C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\dist\osc.js:71:18)
    at osc.UDPPort.emit (node:events:513:28)
    at osc.UDPPort.emit (node:domain:489:12)
    at osc.firePacketEvents (C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\node_modules\osc\src\osc-transports.js:25:18)
    at p.decodeOSC (C:\Work\repos\companion-module-dev\companion-module-zoom-osc-iso\node_modules\osc\src\osc-transports.js:85:17)
    at osc.UDPPort.emit (node:events:513:28)
    at osc.UDPPort.emit (node:domain:489:12)

Node.js v18.14.2
```

The error happens in the osc.ts file in the processData method for the roleChanged switch statement.

Code that causes the error is the first line in the if user role is host or co-host.

```typescript
const index = this.instance.ZoomGroupData[0].users.findIndex((id) => id.zoomID === zoomId);
```

full code: 

```typescript
case 'roleChanged':
    // this.instance.log('debug', 'receiving:' + JSON.stringify(data))
    if ((0, utils_1.userExist)(zoomId, this.instance.ZoomUserData)) {
        this.instance.ZoomUserData[zoomId].userRole = data.args[4].value;
    }
    if (data.args[4].value === UserRole.Participant) {
        const index = this.instance.ZoomGroupData[0].users.findIndex((id) => id.zoomID === zoomId);
        delete this.instance.ZoomGroupData[0].users[index];
        this.updateLoop = true;
    }
    else if (data.args[4].value === UserRole.Host || data.args[4].value === UserRole.CoHost) {
        const index = this.instance.ZoomGroupData[0].users.findIndex((id) => id.zoomID === zoomId);
        if (index === -1) {
            this.instance.ZoomGroupData[0].users.push({
                zoomID: zoomId,
                userName: data.args[1].value,
            });
            this.instance.log('debug', `added host: ${data.args[1].value}`);
        }
        this.updateLoop = true;
    }
    this.instance.UpdateVariablesValues();
    break;
```
