### ISSUE TITLE
Reorganize ZoomISO Presets

### ISSUE THREAD

**Issue by AndrewCarluccio** [bitfocus/companion-module-zoom-osc-iso#79]
Right now, there is one preset category for ZoomISO called "ZoomISO Output Actions" but it only shows selecting and applying outputs. There is no preset category for the other ZoomISO actions. Let's make the following changes:

- Rename "ZoomISO Output Actions" to "ZoomISO Selections" (leave contents alone)
- Add new preset category "ZoomISO Actions" with the following actions:

output ISO (rename to "Set User to Output")
addOutput 
delete Output 
disableOutput
enableOutput 
set Output Count
set Output Embedded Audio
set Output Name
set Output Selection
setOutputMode
setOutputType
Standby ISO Engine
Start ISO Engine
Stop ISO Engine
set Video Loss Mode
audio ISO  (rename to "Set User to Audio Channel")
set Audio Gain Reduction 
set Audio Selection
set Output Embedded Audio
setAudioMode

**Comment by JeffreyDavidsz** [comment]
4ed51ce48790502c7a2a0e27bb54077e92b9aa2b
