### ISSUE TITLE
OSC___ISO_module: Start Cloud Recording does not start cloud recording

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#83]
Companion Version 3.0.0+5781-beta-8cf720a0
ZoomOSC Version 4.2.0 (2023.03.28.07.55)

- 1st effort upon starting a new meeting and making the OSC client a co-host.
- Executing Start Cloud Recording action will not start the cloud recording until after you manually start the recording first, within the client interface. Then Start/Stop Cloud Recording works fine.

Not sure if this is related or not... but, I was attempting to replicate this by removing co-host and then adding co-host back, when I saw errors in the Companion log when adding co-host.

This is what gets produced as an error. It displays in red in the console...

`error: /Applications/__Companion Apps/Companion 3.0/Companion.app/Contents/Resources/bundled-modules/zoom-osc-iso/main.js:2
(()=>{var e={2351:(e,t,n)=>{"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.GetActions=t.ActionId=void 0;const o=n(4499),i=n(6787),s=!0,r=!1;var a,c;!function(e){e[e.SingleSelection=1]="SingleSelection",e[e.MultiSelection=0]="MultiSelection",e[e.ToggleSelection=2]="ToggleSelection"}(a||(a={})),function(e){e.setAudioGainReduction="set_AudioGain_Reduction",e.setOutputSelection="set_Output_Selection",e.setAudioSelection="set_Audio_Selection",e.setOutputEmbeddedAudio="set_Output_Embedded_Audio",e.setVideoLossMode="set_VideoLoss_Mode",e.setOutputName="set_Output_Name",e.deleteOutput="delete_Output",e.outputISO="output_ISO",e.audioISO="audio_ISO",e.startISOEngine="start_ISO_Engine",e.stopISOEngine="stop_ISO_Engine",e.standbyISOEngine="standby_ISO_Engine",e.addOutput="add_Output",e.setOutputCount="set_Output_Count",e.enableOutput="enable_Output",e.disableOutput="disable_Output",e.loadISOConfig="load_ISO_Config",e.saveISOConfig="save_ISO_Config",e.mergeISOConfig="merge_ISO_Config",e.getConfigPath="get_Config_Path",e.setOutputMode="set_Output_Mode",e.setOutputType="set_Output_Type",e.setAudioMode="set_Audio_Mode",e.acceptRecordingConsent="accept_Recording_Consent",e.selectionMethod="selection_Method",e.selectUser="select_User",e.selectUserByName="select_User_By_Name",e.selectGroup="select_Group",e.selectUserFromGroupPosition="select_User_From_Group_Position",e.selectFromGalleryPosition="select_From_Gallery_Position",e.selectFromIndexPosition="select_From_Index_Position",e.clearParticipants="clear_Participants",e.addToGroup="add_To_Group",e.clearGroup="clear_Group",e.removeFromGroup="remove_From_Group",e.rename="rename",e.renameGroup="rename_Group",e.nextParticipants="next_Participants",e.previousParticipants="previous_Participants",e.resetParticipants="reset_Participants",e.selectOutput="select_Output",e.selectAudioChannel="select_Audio_Channel",e.applyOutput="apply_Output",e.applyChannel="apply_Channel",e.applyOutputs="apply_Outputs",e.pin="pin",e.addPin="add_Pin",e.openBreakoutRooms="open_Breakout_Rooms",e.unpin="unpin",e.clearPins="clear_Pins",e.togglePin="toggle_Pin",e.pinScreen2="pin_Screen2",e.unPinScreen2="unPinScreen2",e.clearPinsScreen2="clearPinsScreen2",e.togglePinScreen2="togglePinScreen2",e.addSpotlight="addSpotlight",e.spotLight="spotLight",e.unSpotLight="unSpotLight",e.toggleSpotlight="toggleSpotlight",e.turnVideoOn="turnVideoOn",e.turnVideoOff="turnVideoOff",e.toggleVideoState="toggleVideoState",e.mute="mute",e.unmute="unmute",e.toggleMuteState="toggleMuteState",e.raiseHand="raiseHand",e.lowerHand="lowerHand",e.toggleHand="toggleHand",e.makeHost="makeHost",e.makeCoHost="makeCoHost",e.revokeCoHost="revokeCoHost",e.reclaimHost="reclaimHost",e.makePanelist="makePanelist",e.makeAttendee="makeAttendee",e.ejectParticipant="ejectParticipant",e.returnSelfToMainMeeting="returnSelfToMainMeeting",e.admitSomeoneFromWaitingRoom="admitSomeoneFromWaitingRoom",e.sendSomeoneToWaitingRoom="sendSomeoneToWaitingRoom",e.allowWebinarAttendeeToSpeak="allowWebinarAttendeeToSpeak",e.disallowToSpeak="disallowToSpeak",e.startScreenShareWithPrimaryScreen="startScreenShareWithPrimaryScreen",e.cycleSharedCameraToNextAvailable="cycleSharedCameraToNextAvailable",e.gotoNextGalleryPage="gotoNextGalleryPage",e.gotoPreviousGalleryPage="gotoPreviousGalleryPage",e.stopSharing="stopSharing",e.allowToRecord="allowToRecord",e.disallowToRecord="disallowToRecord",e.hideNonVideoParticipants="hideNonVideoParticipants",e.showNonVideoParticipants="showNonVideoParticipants",e.setSpeakerView="setSpeakerView",e.requestOrderOfGalleryView="requestOrderOfGalleryView",e.configureBreakoutRooms="configureBreakoutRooms",e.startCameraShare="startCameraShare",e.listUsers="listUsers",e.pingZoomOSC="pingZoomOSC",e.disableWaitingRoom="disableWaitingRoom",e.enableWaitingRoom="enableWaitingRoom",e.requestGalleryCount="requestGalleryCount",e.startLocalRecording="startLocalRecording",e.sendParticipantToBreakoutRoom="sendParticipantToBreakoutRoom",e.hideUserNamesOnVideo="hideUserNamesOnVideo",e.showUserNamesOnVideo="showUserNamesOnVideo",e.enableOriginalSound="enableOriginalSound",e.disableOriginalSound="disableOriginalSound",e.enableHDVideo="enableHDVideo",e.disableHDVideo="disableHDVideo",e.enableMirrorVideo="enableMirrorVideo",e.disableMirrorVideo="disableMirrorVideo",e.enableOptimizeVideoForSharing="enableOptimizeVideoForSharing",e.disableOptimizeVideoForSharing="disableOptimizeVideoForSharing",e.disableComputerSoundWhenSharing="disableComputerSoundWhenSharing",e.removeParticipantFromBreakoutRoom="removeParticipantFromBreakoutRoom",e.assignParticipantToBreakoutRoom="assignParticipantToBreakoutRoom",e.unassignParticipantFromBreakoutRoom="unassignParticipantFromBreakoutRoom",e.setGalleryView="setGalleryView",e.muteAll="muteAll",e.unmuteAll="unmuteAll",e.muteAllExcept="muteAllExcept",e.muteAllExceptHost="muteAllExceptHost",e.clearSpotlight="clearSpotlight",e.enableComputerSoundWhenSharing="enableComputerSoundWhenSharing",e.disableUsersToUnmute="disableUsersToUnmute",e.lowerAllHands="lowerAllHands",e.enableUsersToUnmute="enableUsersToUnmute",e.closeBreakoutRooms="closeBreakoutRooms",e.deleteAllBreakoutRooms="deleteAllBreakoutRooms",e.admitEveryoneFromWaitingRoom="admitEveryoneFromWaitingRoom",e.ejectAll="ejectAll",e.pauseLocalRecording="pauseLocalRecording",e.resumeLocalRecording="resumeLocalRecording",e.stopLocalRecording="stopLocalRecording",e.startCloudRecording="startCloudRecording",e.requestListOfBreakoutRooms="requestListOfBreakoutRooms",e.leaveMeeting="leaveMeeting",e.resumeCloudRecording="resumeCloudRecording",e.stopCloudRecording="stopCloudRecording",e.pauseCloudRecording="pauseCloudRecording",e.endMeeting="endMeeting",e.SetWindowPosition="SetWindowPosition",e.SetWindowSize="SetWindowSize",e.customCommandWithArguments="customCommandWithArguments",e.customCommand="customCommand",e.ZAKStartMeeting="ZAKStartMeeting",e.ZAKJoinMeeting="ZAKJoinMeeting",e.sendMessageToWaitingRoom="sendMessageToWaitingRoom",e.startShareWithWindow="startShareWithWindow",e.startAudioShare="startAudioShare",e.startScreenShare="startScreenShare",e.sendAChatViaDM="sendAChatViaDM",e.sendAChatToEveryone="sendAChatToEveryone",e.createBreakoutRoom="createBreakoutRoom",e.deleteBreakoutRoom="deleteBreakoutRoom",e.setMicLevel="setMicLevel",e.setMicDevice="setMicDevice",e.setSpeakerDevice="setSpeakerDevice",e.setSpeakerVolume="setSpeakerVolume",e.setCameraDevice="setCameraDevice",e.setVideoFilter="setVideoFilter",e.setVirtualBackground="setVirtualBackground",e.broadcastMessageToBreakoutRooms="broadcastMessageToBreakoutRooms",e.joinMeeting="joinMeeting",e.restorePreviousSelection="restorePreviousSelection"}(c=t.ActionId||(t.ActionId={})),t.GetActions=function(e){const t=[{id:"0",label:"no users"}],n=[],l=[];let d="0";if(e.ZoomUserData){t.length=0;for(const n in e.ZoomUserData)if(Object.prototype.hasOwnProperty.call(e.ZoomUserData,n)){const o=e.ZoomUserData[n];t.push({id:o.zoomId.toString(),label:o.userName}),d=o.zoomId.toString()}}e.ZoomGroupData.forEach(((e,t)=>{n.push({id:t.toString(),label:e.groupName}),0!=t&&l.push({id:t.toString(),label:e.groupName})}));const u=[];for(let e=1;e<50;e++)u.push({id:e.toString(),label:`Position ${e}`});const p=[];for(let e=1;e<1e3;e++)p.push({id:e.toString(),label:`Participant ${e}`});const h=[];for(let t=1;t<(0===Object.keys(e.ZoomAudioRoutingData).length?9:Object.keys(e.ZoomAudioRoutingData).length+1);t++)h.push({id:t,label:`Output ${t}`});const f={type:"dropdown",label:"User",id:"user",default:d,choices:t},m={type:"dropdown",label:"Position",id:"position",default:"0",choices:u},g={type:"dropdown",label:"Position",id:"position",default:"0",choices:p},b={type:"dropdown",label:"Group",id:"group",default:"1",choices:n},_={type:"dropdown",label:"Group",id:"group",default:"1",choices:l},y={type:"dropdown",label:"Output",id:"output",default:1,choices:h},S=(t,n)=>{const o=t.options.command,i=t.options.args;e.log("debug",`Sending ${JSON.stringify(o)}, with arguments ${JSON.stringify(i)}`),e.OSC&&e.OSC.sendCommand(o,i)},v={[c.setAudioGainReduction]:{name:"set Audio G`

**Comment by JeffreyDavidsz** [comment]
Latest PR was added yesterday or the day before
