### ISSUE TITLE
Maintaining State is Module has to be Reset

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#84]
Would it be possible to recover the state of Group memberships, Custom Variables, etc when the module needs to be reset?

It has been the case that when Gallery data won't update correctly or at all, the decision has to be made to reset the module. If this is during a live event and much investment has been made in group management, this ends up causing some significant issues for the operator.

**Comment by AndrewCarluccio** [comment]
I would suggest that the solution is #73 

The reset of the module needs to be complete, otherwise it isn't really a reset and something bad could carry over in my opinion. This would open the door to an unrecoverable state. The serialization plan in #73 is the better solution in my opinion.
