### ISSUE TITLE
Admit (Selected) from Waiting Room removes Selections upon completion

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion-module-zoom-osc-iso#87]
When sending (selected) participants to the waiting room the selections remain selected upon completion. Although, when admitting (selected) participants from the waiting room the selections or no longer actively selected upon completion.

The initial selections just should remain selected in the workflow.

**Comment by AndrewCarluccio** [comment]
This may not be technically possible since the selected users are given new Zoom IDs when they enter the meeting. So the people you selected actually go offline and new people with the same name enter. The selected ZoomIDs would be invalid.
