### ISSUE TITLE
Performance Question: Do we need to loop through all of the ZoomUserData for single user actions

### ISSUE THREAD

**Issue by digitaldrummerj** [bitfocus/companion-module-zoom-osc-iso#96]
@JeffreyDavidsz @AndrewCarluccio looking through the code, I have noticed a few places that are a single user action but in the action it is looping through all of the ZoomUserData looking for the user.  Do we need the loop or can we just use `instance.ZoomUserData[key]` instead of the loop?

**Comment by JeffreyDavidsz** [comment]
If you could point out some lines, I can check. As long as it doesn't kill the multiple selection options I'm fine with it

**Comment by digitaldrummerj** [comment]
@JeffreyDavidsz looking at it more there are two places in the action.ts file.

* actionId.selectUserByName is a spot where there is a loop by no return statement to exit the for loop after the user is found.
* actionId.removeFromGroup if the `userName is undefined or userName is !== ''` meaning you put a user into the input box instead of doing pre-select then it loops through all of the users.  I think this loop can be removed and just get the user from the `instance.ZoomUserData[key]`
